import colorsys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont, ImageFilter

from services.badge.renderers.base_renderer import BaseRenderer
import textwrap

from services.badge.templates.diamond_recolor import recolor_diamond_badge


class DiamondRenderer(BaseRenderer):
    """
    Diamond renderer tuned to match the real Microsoft badge:
      * Big BOLD white title (no heavy stroke -> not over-thick).
      * Program category in a PALE ICE-BLUE tint, drawn with visible
        letter-spacing/tracking (all-caps), like the real badge.
      * Activity/track text in a near-neutral pale gray-blue (NOT the
        same saturated tint as the program category), thinner weight.
      * Date in BOLD, with a touch of tracking so the digits read
        openly instead of tight/cramped, like the real badge.
      * All text CENTER-anchored on fraction-of-height lines, so vertical
        placement is independent of the auto-fit font size.

    NOTE ON CALIBRATION: every F_*, W_* and colour-tint constant below was
    measured directly off the real reference badge (pixel analysis of the
    hexagon geometry, text bounding boxes and sampled text colours), not
    guessed. See the inline comments next to each constant.
    """

    # ------------------------------------------------------------------
    # LAYOUT FRACTIONS (vertical CENTRES, fraction of template height)
    # ------------------------------------------------------------------
    # RE-CALIBRATED from a fresh pixel-level bounding-box measurement of
    # the 732x887 reference badge (top/bottom edges of each text block
    # located via a colour/luminance mask that excludes the outer gray
    # canvas, the hexagon border stroke, and the bottom ribbon fold).
    F_LOGO_TOP = 0.178      # Microsoft logo TOP edge -- was 0.215, logo was
                            # rendering ~33px (3.7% of height) too LOW.
    F_PROGRAM = 0.293       # reference centre: about 260 px on 887 px image
    F_SEPARATOR = 0.357     # divider line              (measured: 0.357)
    F_ACTIVITY = 0.436      # reference centre: about 387 px on 887 px image
    F_TITLE = 0.519         # reference centre: about 460 px on 887 px image
    F_DATE = 0.677          # reference centre: about 600 px on 887 px image

    # Separator half-width as a fraction of template width.
    # Re-measured: the line's real half-width is 0.104, not 0.118 -- the
    # old value drew it about 20px (10px per side) too wide.
    SEPARATOR_HALF_W = 0.104
    SEPARATOR_WIDTH = 3

    # Target text widths as a fraction of the TEMPLATE WIDTH.
    # Re-measured directly from the reference badge's text bounding boxes.
    W_TITLE = 0.600
    W_ACTIVITY = 0.395
    # W_PROGRAM/W_DATE widened below (see PROGRAM_FONT_MAX_FRAC /
    # DATE_FONT_MAX_FRAC comment) -- the old 0.418/0.123 values were not
    # actually the binding constraint on a 2048px-tall canvas; the real
    # problem was the font-size CEILING (see below), but once that
    # ceiling is raised these targets also need to be wide enough that
    # the bigger font isn't immediately shrunk back down again.
    W_PROGRAM = 0.600   # was 0.418 -- matches the safely-verified W_TITLE
    W_DATE = 0.170       # was 0.123

    # ------------------------------------------------------------------
    # TRACKED-TEXT FONT-SIZE CEILINGS (category + date)
    # ------------------------------------------------------------------
    # Pixel-measured against the real reference badge (2048x2048 export):
    # the category line ("Dynamics 365" / "365" digits used as a clean,
    # descender-free measuring stick) has a cap-height of ~58px, and the
    # date ("2025") has a cap-height of ~62px on that same 2048-tall
    # canvas. The equivalent text in badges generated by THIS renderer
    # measured only ~24px (category) and ~37px (date) -- i.e. the
    # tracked-font auto-fit was settling at max_size WITHOUT ever
    # touching the available W_PROGRAM/W_DATE width (there was plenty of
    # spare room left over), which means the old max_size ceiling
    # (self.PROGRAM_FONT_SIZE + 30 / self.DATE_FONT_SIZE + 20) was the
    # real bottleneck, not the width. These new *_FONT_MAX_FRAC
    # constants replace that ceiling with a canvas-height fraction
    # (consistent with every other measurement in this file being
    # resolution-independent) sized generously above the ~58px/~62px
    # targets, so the width check above becomes the true governor and
    # the auto-shrink safety net still protects any longer program name
    # or date string from overflowing the hexagon face.
    PROGRAM_FONT_MAX_FRAC = 0.044   # -> ~90px cap-ceiling on a 2048px canvas
    DATE_FONT_MAX_FRAC = 0.046      # -> ~94px cap-ceiling on a 2048px canvas

    # Logo width as a fraction of template width.
    # Re-measured: the real logo (4-square glyph + wordmark) spans about
    # 220px on the 732px-wide reference (~0.30), not 0.28 -- the old
    # value rendered the logo about 7% too small.
    LOGO_W = 0.30

    # ------------------------------------------------------------------
    # TEXT COLOUR TINTS
    # ------------------------------------------------------------------
    # Each text colour is derived from the badge's theme "outer" light
    # stop (e.g. "#AAD0F0" for blue) by nudging lightness/saturation in
    # HLS space. The (delta_lightness, delta_saturation) pairs below were
    # solved so that, starting from the blue theme's own light stop, they
    # reproduce the EXACT colours sampled from the reference badge:
    #   program category -> #DBEDF9   (pale ice-blue, still tinted)
    #   activity banner   -> #E7EBEE   (near-neutral pale gray, desaturated)
    #   separator line    -> #EFF1F3   (essentially white)
    # Deriving them from the theme colour (instead of hard-coding one
    # fixed hex) keeps purple/teal themes coordinated the same way.
    PROGRAM_TINT = (0.1137, 0.0143)
    ACTIVITY_TINT = (0.1157, -0.5293)
    SEPARATOR_TINT = (0.1412, -0.5571)

    # Letter-spacing (tracking), as a fraction of font size. Measured from
    # the reference badge's rendered letter gaps.
    PROGRAM_TRACKING_RATIO = 0.22
    DATE_TRACKING_RATIO = 0.25

    # ------------------------------------------------------------------
    # ACTIVITY BANNER vertical safety margins (fraction of height)
    # ------------------------------------------------------------------
    # The activity block is CENTRED on F_ACTIVITY and must never touch the
    # separator above it or the main title below it. These small gaps are
    # subtracted from the space available between those neighbours; the
    # activity font then shrinks (and the text re-wraps) so the whole
    # block fits inside what's left. Kept intentionally small so a normal
    # single-line activity still renders at full size, exactly like the
    # reference badge -- only longer/multi-line values are shrunk.
    ACTIVITY_TOP_GAP = 0.006   # clearance below the separator line
    ACTIVITY_BOTTOM_GAP = 0.006  # clearance above the title's top edge
    ACTIVITY_MIN_FONT = 20     # never shrink the activity text below this

    def __init__(self):
        super().__init__()

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------
    def _y(self, image, frac):
        return int(round(image.height * frac))

    def _light_colour(self, grade, default="#C6B1DE"):
        try:
            text = str(grade).replace("\u2013", "-")
            hexes = [p.strip() for p in text.split("-") if p.strip().startswith("#")]
            if hexes:
                return hexes[-1]
        except Exception:
            pass
        return default

    def _tinted_colour(self, grade, tint, default="#AAD0F0"):
        """Nudge the theme's light stop toward one of the reference's
        measured text colours (see PROGRAM_TINT / ACTIVITY_TINT /
        SEPARATOR_TINT above) using an HLS lightness/saturation delta."""
        hexcol = self._light_colour(grade, default=default)
        hexcol = hexcol.lstrip("#")
        if len(hexcol) == 3:
            hexcol = "".join(ch * 2 for ch in hexcol)
        try:
            r, g, b = (int(hexcol[i:i + 2], 16) for i in (0, 2, 4))
        except Exception:
            r, g, b = (170, 208, 240)  # fallback: blue theme light stop

        h, l, s = colorsys.rgb_to_hls(r / 255.0, g / 255.0, b / 255.0)
        dl, ds = tint
        l = min(1.0, max(0.0, l + dl))
        s = min(1.0, max(0.0, s + ds))
        rr, gg, bb = colorsys.hls_to_rgb(h, l, s)
        return (round(rr * 255), round(gg * 255), round(bb * 255))

    def _fit_font(self, draw, text, target_w, max_size,
                  weight="semibold", min_size=18):
        """Largest font of the given weight whose width for `text` is
        <= target_w (auto-fit: big when short, shrinks when long)."""
        size = max_size
        while size > min_size:
            font = self.get_font(size, weight=weight)
            if draw.textbbox((0, 0), text, font=font)[2] <= target_w:
                return font
            size -= 2
        return self.get_font(min_size, weight=weight)

    # ------------------------------------------------------------------
    # WIDTH + HEIGHT aware fitting (used by the activity banner).
    #
    # Unlike _fit_font (which only checks horizontal width and therefore
    # lets a multi-line block grow DOWNWARD past its neighbours), this
    # picks the largest font whose wrapped block fits BOTH the target
    # width AND a maximum block height. The text is re-wrapped by pixel
    # width at every trial size, so a long/character-heavy value shrinks
    # to fit its allotted space instead of overflowing into the title.
    # The vertical CENTRE stays pinned to F_ACTIVITY, so the spacing to
    # the other lines is identical on every badge -- only the size adapts.
    # ------------------------------------------------------------------
    def _wrap_pixels(self, draw, text, font, max_w):
        """Greedy word-wrap by measured pixel width (fewest lines that fit
        max_w at this font size)."""
        words = str(text).split()
        if not words:
            return [str(text)]
        lines, cur = [], ""
        for w in words:
            trial = (cur + " " + w).strip()
            if not cur or draw.textbbox((0, 0), trial, font=font)[2] <= max_w:
                cur = trial
            else:
                lines.append(cur)
                cur = w
        if cur:
            lines.append(cur)
        return lines

    def _balanced_wrap(self, draw, text, font, max_w, max_lines):
        """Wrap `text` into at most `max_lines` lines, every line <= max_w,
        preferring an EVEN split (so a 2-line block reads as two balanced
        halves instead of one long line + one orphan word). Returns the
        line list, or None if it simply cannot fit in max_lines at this
        font size."""
        words = str(text).split()
        if not words:
            return [str(text)]

        def fits(line):
            return draw.textbbox((0, 0), line, font=font)[2] <= max_w

        # Fast path: everything on one line.
        if fits(" ".join(words)):
            return [" ".join(words)]

        # Try k = 2 .. max_lines, choosing the split that minimises the
        # WIDEST line (most balanced) while keeping every line within max_w.
        for k in range(2, max_lines + 1):
            best, best_metric = None, None
            # enumerate all ways to break `words` into k contiguous groups
            import itertools
            n = len(words)
            for cuts in itertools.combinations(range(1, n), k - 1):
                idx = [0, *cuts, n]
                groups = [" ".join(words[idx[j]:idx[j + 1]]) for j in range(k)]
                widths = [draw.textbbox((0, 0), g, font=font)[2] for g in groups]
                if max(widths) > max_w:
                    continue
                metric = max(widths)  # minimise the widest line
                if best_metric is None or metric < best_metric:
                    best, best_metric = groups, metric
            if best is not None:
                return best
        return None  # cannot fit within max_lines at this size

    def _fit_wrapped_block(self, draw, text, target_w, max_block_h,
                           max_size, weight="semibold",
                           line_gap=1.16, min_size=14, max_lines=3):
        """Largest font whose BALANCED wrapped block fits target_w wide AND
        max_block_h tall (within max_lines). Returns (font, lines)."""
        size = max_size
        while size >= min_size:
            font = self.get_font(size, weight=weight)
            lines = self._balanced_wrap(draw, text, font, target_w, max_lines)
            if lines is not None:
                asc, desc = font.getmetrics()
                lh = int(round((asc + desc) * line_gap))
                if lh * len(lines) <= max_block_h:
                    return font, lines
            size -= 2
        # Last resort: shrink onto whatever fits width, ignore balance.
        font = self.get_font(min_size, weight=weight)
        return font, self._wrap_pixels(draw, text, font, target_w)

    def _title_top_frac(self, image, title):
        """Top edge (as a fraction of height) of the main title block,
        so the activity banner can be kept clear of it. Mirrors the
        sizing used by draw_main_title."""
        if not title:
            return self.F_TITLE - 0.04
        draw = ImageDraw.Draw(image)
        t = str(title).upper()
        target_w = int(image.width * self.W_TITLE)
        font = self._fit_font(
            draw, t, target_w,
            max_size=self.MAIN_TITLE_FONT_SIZE + 30, weight="bold",
        )
        asc, desc = font.getmetrics()
        lh = (asc + desc) * 1.16
        cy = image.height * self.F_TITLE
        return (cy - lh / 2) / image.height

    def _draw_block_centered(self, image, lines, center_frac, font,
                             colour, stroke=0, line_gap=1.16):
        """Draw line(s) centred horizontally and vertically around
        center_frac (fraction of height). anchor='mm' makes placement
        independent of the font size."""
        draw = ImageDraw.Draw(image)
        cx = image.width / 2
        cy = image.height * center_frac
        asc, desc = font.getmetrics()
        lh = int(round((asc + desc) * line_gap))
        total = lh * len(lines)
        first_cy = cy - total / 2 + lh / 2
        for i, line in enumerate(lines):
            draw.text(
                (cx, first_cy + i * lh), line, font=font, fill=colour,
                anchor="mm", stroke_width=stroke, stroke_fill=colour,
            )

    # ------------------------------------------------------------------
    # TRACKED (letter-spaced) TEXT drawing -- used for the program
    # category ("COPILOT STACK" style) and the date, both of which show
    # visible tracking in the reference badge.
    # ------------------------------------------------------------------
    def _tracked_width(self, draw, text, font, tracking):
        total = 0.0
        n = len(text)
        for i, ch in enumerate(text):
            if ch == " ":
                w = tracking * 3.0
            else:
                bbox = draw.textbbox((0, 0), ch, font=font)
                w = bbox[2] - bbox[0]
            total += w
            if i < n - 1:
                total += tracking
        return total

    def _fit_tracked_font(self, draw, text, target_w, max_size,
                          weight="regular", min_size=16, tracking_ratio=0.22):
        size = max_size
        while size > min_size:
            font = self.get_font(size, weight=weight)
            tracking = size * tracking_ratio
            if self._tracked_width(draw, text, font, tracking) <= target_w:
                return font, tracking
            size -= 2
        font = self.get_font(min_size, weight=weight)
        return font, min_size * tracking_ratio

    def _draw_tracked_line(self, image, text, y_center, font, tracking, colour):
        draw = ImageDraw.Draw(image)
        total_w = self._tracked_width(draw, text, font, tracking)
        x = image.width / 2 - total_w / 2
        n = len(text)
        for i, ch in enumerate(text):
            if ch == " ":
                x += tracking * 3.0
                continue
            draw.text((x, y_center), ch, font=font, fill=colour, anchor="lm")
            bbox = draw.textbbox((0, 0), ch, font=font)
            x += bbox[2] - bbox[0]
            if i < n - 1:
                x += tracking

    def _draw_tracked_block_centered(self, image, lines, center_frac, font,
                                     tracking, colour, line_gap=1.16):
        asc, desc = font.getmetrics()
        lh = int(round((asc + desc) * line_gap))
        total = lh * len(lines)
        cy = image.height * center_frac
        first_cy = cy - total / 2 + lh / 2
        for i, line in enumerate(lines):
            self._draw_tracked_line(
                image, line, first_cy + i * lh, font, tracking, colour
            )

    # ------------------------------------------------------------------
    def load_template(self, badge):
        template_path = (
            Path(__file__).parent.parent
            / "templates"
            / "diamond_template.png"
        )

        base = Image.open(template_path).convert("RGBA")

        print("DEBUG TEMPLATE PATH:", template_path)
        print("DEBUG TEMPLATE SIZE:", base.size)
        print("DEBUG TEMPLATE MODE:", base.mode)
        print("DEBUG TOP-LEFT PIXEL:", base.getpixel((0, 0)))
        print("DEBUG ALPHA EXTREMA:", base.getchannel("A").getextrema())

        # Apply the requested badge colours before drawing any text or logos.
        # Previously this method returned the original blue template directly,
        # so every generated diamond stayed blue regardless of the selected colour.
        recolored = recolor_diamond_badge(
            base,
            outer_grade=badge.outer_colour,
            inner_grade=badge.inner_colour,
        )

        return recolored

    def _prep_logo(self, logo):
        """Prepare the Microsoft logo: knock out any white background,
        whiten the gray wordmark, trim to visible bounds, and thicken the
        white wordmark slightly (coloured squares untouched)."""
        import numpy as np
        a = np.array(logo.convert("RGBA")).astype(float)
        rgb = a[:, :, :3]

        # Remove near-white background -> transparent.
        near_white = (rgb.min(2) > 235) & (a[:, :, 3] > 10)
        a[near_white, 3] = 0

        # Whiten the gray wordmark (low saturation), keep coloured squares.
        op = a[:, :, 3] > 10
        mx = rgb.max(2)
        mn = rgb.min(2)
        sat = (mx - mn) / (mx + 1e-6)
        gray = op & (sat < 0.25)
        a[gray, 0] = 255
        a[gray, 1] = 255
        a[gray, 2] = 255

        out = Image.fromarray(a.astype("uint8"), "RGBA")
        bbox = out.getbbox()
        out = out.crop(bbox) if bbox else out

        # Thicken ONLY the white wordmark (squares stay intact).
        #
        # IMPORTANT: this used to threshold alpha into a binary mask,
        # dilate THAT mask, then stamp the newly-covered ring fully
        # opaque. That throws away the source PNG's antialiasing (which
        # lives entirely in partial alpha values -- the RGB is a flat
        # gray/white) and replaces the soft edge with a hard 0->255
        # cliff. At this logo's native resolution (384x82) that hard
        # cliff is only 1px, but once the badge scales the logo up it
        # reads as a visible stair-stepped outline around every letter.
        #
        # Fix: dilate the wordmark's ALPHA VALUES directly (grayscale
        # max filter) instead of a thresholded mask. A pixel just
        # outside the glyph then inherits the (possibly partial) alpha
        # of its nearest wordmark neighbour, so growth still ends in a
        # soft falloff rather than a hard edge.
        arr = np.array(out)
        rgb2 = arr[:, :, :3].astype(float)
        al2 = arr[:, :, 3].astype(float)
        s2 = (rgb2.max(2) - rgb2.min(2)) / (rgb2.max(2) + 1e-6)
        wm = (al2 > 10) & (s2 < 0.25)          # white wordmark pixels only

        wm_alpha_only = np.where(wm, al2, 0).astype("uint8")
        wm_alpha_dilated = np.array(
            Image.fromarray(wm_alpha_only).filter(ImageFilter.MaxFilter(3))
        ).astype(float)

        grown = wm_alpha_dilated > al2
        arr[grown, 0] = 255
        arr[grown, 1] = 255
        arr[grown, 2] = 255
        arr[:, :, 3] = np.maximum(al2, wm_alpha_dilated).astype("uint8")
        out = Image.fromarray(arr, "RGBA")

        return out

    def draw_microsoft_header(self, image, badge):
        logo_dir = Path(__file__).parent.parent / "logo"

        # Prefer the HI-RES logo; _prep_logo strips its white background.
        logo_path = logo_dir / "microsoft_logos.png"
        if not logo_path.exists():
            logo_path = logo_dir / "microsoft_logo.png"
        if not logo_path.exists():
            raise FileNotFoundError(f"Microsoft logo not found: {logo_path}")

        logo = Image.open(logo_path).convert("RGBA")
        logo = self._prep_logo(logo)

        target_w = max(200, int(image.width * self.LOGO_W))
        scale = target_w / logo.width
        target_h = max(1, int(round(logo.height * scale)))
        logo = logo.resize((target_w, target_h), Image.Resampling.LANCZOS)

        start_x = (image.width - logo.width) // 2
        start_y = self._y(image, self.F_LOGO_TOP)
        image.paste(logo, (start_x, start_y), logo)

    def draw_program_category(self, image, text, badge=None):
        if not text:
            return
        draw = ImageDraw.Draw(image)
        colour = self._tinted_colour(
            badge.outer_colour if badge is not None else None,
            self.PROGRAM_TINT,
        )
        target_w = int(image.width * self.W_PROGRAM)
        text_up = text.upper()
        lines = textwrap.wrap(text_up, width=20) or [text_up]
        widest = max(lines, key=len)
        # THINNER (regular) letter-spaced text to match the real badge's
        # tracked all-caps style.
        # NOTE: max_size now comes from PROGRAM_FONT_MAX_FRAC (a canvas-
        # height fraction), not "self.PROGRAM_FONT_SIZE + 30" -- that old
        # ceiling was measured as only producing a ~24px cap-height on a
        # 2048px canvas, well under half the real badge's ~58px. See the
        # PROGRAM_FONT_MAX_FRAC comment above for the full measurement.
        font, tracking = self._fit_tracked_font(
            draw, widest, target_w,
            max_size=int(image.height * self.PROGRAM_FONT_MAX_FRAC), weight="regular",
            tracking_ratio=self.PROGRAM_TRACKING_RATIO,
        )
        self._draw_tracked_block_centered(
            image, lines, self.F_PROGRAM, font, tracking, colour
        )

    def draw_separator(self, image, badge=None):
        draw = ImageDraw.Draw(image)
        center_x = image.width // 2
        y = self._y(image, self.F_SEPARATOR)
        half = int(round(image.width * self.SEPARATOR_HALF_W))
        colour = self._tinted_colour(
            badge.outer_colour if badge is not None else None,
            self.SEPARATOR_TINT,
        )
        draw.line(
            (center_x - half, y, center_x + half, y),
            fill=colour, width=self.SEPARATOR_WIDTH,
        )

    def draw_activity_banner(self, image, text, badge=None):
        if not text:
            return
        draw = ImageDraw.Draw(image)
        # Near-neutral pale gray-blue -- noticeably LESS saturated than
        # the program category text, per the reference badge.
        colour = self._tinted_colour(
            badge.outer_colour if badge is not None else None,
            self.ACTIVITY_TINT,
        )
        target_w = int(image.width * self.W_ACTIVITY)

        # --------------------------------------------------------------
        # Height-aware auto-fit so long / character-heavy activity names
        # shrink to fit instead of overflowing into the title (the old
        # width-only fit let "Frontier Transformation Engineer" spill into
        # "TITAN"), WITHOUT over-shrinking it onto one tiny line.
        #
        # KEY FIX: the block is centred in, and allowed to use the FULL
        # vertical gap between the separator and the title's top edge --
        # NOT a tight symmetric box around F_ACTIVITY. The title sits
        # closer below the old anchor than the separator sits above it, so
        # a symmetric box wasted ~40% of the real room (~150px of ~249px)
        # and forced the text far smaller than necessary. Centring in the
        # gap keeps the spacing to both neighbours consistent on every
        # badge (always vertically centred in that fixed gap) while giving
        # long names enough room to render as two balanced, readable lines.
        # A short name still fits at full size on one line, exactly like
        # the reference badge -- only long/character-heavy names shrink.
        # --------------------------------------------------------------
        title = badge.achievement_name if badge is not None else None
        band_top = self.F_SEPARATOR + self.ACTIVITY_TOP_GAP
        band_bottom = self._title_top_frac(image, title) - self.ACTIVITY_BOTTOM_GAP
        center_frac = (band_top + band_bottom) / 2.0
        max_block_h = max(1, int(round((band_bottom - band_top) * image.height)))

        font, lines = self._fit_wrapped_block(
            draw, text, target_w, max_block_h,
            max_size=self.ACTIVITY_FONT_SIZE + 30, weight="semibold",
            min_size=self.ACTIVITY_MIN_FONT, max_lines=3,
        )
        self._draw_block_centered(image, lines, center_frac, font, colour)

    def draw_main_title(self, image, text):
        if not text:
            return
        draw = ImageDraw.Draw(image)
        text = text.upper()
        target_w = int(image.width * self.W_TITLE)
        # BOLD, but NO extra stroke (so it isn't over-thick).
        font = self._fit_font(
            draw, text, target_w,
            max_size=self.MAIN_TITLE_FONT_SIZE + 30, weight="bold",
        )
        self._draw_block_centered(
            image, [text], self.F_TITLE, font, "white", stroke=0
        )

    def draw_date(self, image, text):
        if not text:
            return
        draw = ImageDraw.Draw(image)
        target_w = int(image.width * self.W_DATE)
        # BOLD, with a touch of tracking so the digits read openly,
        # matching the reference badge's spaced-out date.
        # NOTE: max_size now comes from DATE_FONT_MAX_FRAC (a canvas-
        # height fraction), not "self.DATE_FONT_SIZE + 20" -- that old
        # ceiling was measured as only producing a ~37px cap-height on a
        # 2048px canvas, well under the real badge's ~62px. See the
        # DATE_FONT_MAX_FRAC comment above for the full measurement.
        font, tracking = self._fit_tracked_font(
            draw, str(text), target_w,
            max_size=int(image.height * self.DATE_FONT_MAX_FRAC), weight="bold",
            tracking_ratio=self.DATE_TRACKING_RATIO,
        )
        y_center = image.height * self.F_DATE
        self._draw_tracked_line(image, str(text), y_center, font, tracking, "white")

    # ------------------------------------------------------------------
    def render_badge(self, badge):
        image = self.load_template(badge)
        self.draw_microsoft_header(image, badge)
        self.draw_program_category(image, badge.program_category, badge)
        self.draw_separator(image, badge)
        self.draw_activity_banner(image, badge.activity_track_name, badge)
        self.draw_main_title(image, badge.achievement_name)
        self.draw_date(image, badge.date)
        # Final square sizing is handled in main.py (fit_to_square).
        return image
